service: authorization-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: dev

  httpApi:
    authorizers:
      basicAuth:
        type: request
        functionName: authorizationService
        identitySource:
          - $request.header.Authorization

functions:
  authorizationService:
    handler: handler.lambda_handler

plugins:
  - serverless-dotenv-plugin
