service: import-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: dev

functions:
  importProducts:
    name: importProducts
    handler: handler.import_products
    events:
      - http:
          path: import
          method: post
          authorizer:
            type: request
            arn: arn:aws:lambda:us-east-1:970547362653:function:authorizationService
