service: import-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: dev

functions:
  importProducts:
    handler: handler.import_products
    events:
      - httpApi:
          path: /import
          method: post
          authorizer:
            type: request
            authorizerId:
              Fn::GetAtt:
                - ImportApiGatewayAuthorizer
                - AuthorizerId
